In [8]:
import numpy as np

filter numpu using any()

In [9]:
sales_data=np.array([[5000,7200,6100,8500],[4200,5100,4800,6300],[9100,8700,9200,10500],[3800,4100,3900,4600]])
max_seales=np.any(sales_data>8000,axis=1)
result=sales_data[max_seales]
print(max_seales)
print(result)

[ True False  True False]
[[ 5000  7200  6100  8500]
 [ 9100  8700  9200 10500]]


filter numpu using where()

In [10]:
customer_rating=np.array([[4.2,3.8,4.5,4.1],[3.1,3.2,2.9,3.3],[4.8,4.7,4.9,4.6],[3.7,3.9,3.5,3.8]])
average_ratings=np.where(np.mean(customer_rating>4.0,axis=1))
highly_ratings=customer_rating[average_ratings]
print(average_ratings)
print(highly_ratings)

(array([0, 2]),)
[[4.2 3.8 4.5 4.1]
 [4.8 4.7 4.9 4.6]]


filter numpu using Extract()

In [11]:
temparature=np.array([[72,85,68,45],[45,65,55,30],[68,75,65,55],[35,60,50,25]])
tem_above=np.extract(temparature>70,temparature)
print(tem_above)

[72 85 75]


filter numpu using marked()

In [12]:
stock_price=np.array([[2.5,-1.3,5.2,0.5],[-0.7,-2.1,-0.5,-1.2],[1.8,2.3,-0.4,1.5],[3.1,-0.8,2.7,4.2]])
negative_stock=np.masked_array(stock_price,stock_price<0)
print(negative_stock)

AttributeError: module 'numpy' has no attribute 'masked_array'

filter numpu using  comress()

In [ ]:
trafic_data=np.array([[1200,1500,1100,1300],[500,450,550,480],[2200,2500,230,2400],[850,900,830,870]])
average_visitor=np.compress(np.mean(trafic_data>1000,axis=1),trafic_data,axis=0)
print(average_visitor)

[[1200 1500 1100 1300]
 [2200 2500  230 2400]]


Multiple condition arise

In [15]:
product_data=np.array([[49.99,4.2,5],[99.99,4.7,120],[19.99,4.0,3],[79.99,4.5,8]])
c1=product_data[:,0]<80
c2=product_data[:,1]>4.0
c3=product_data[:,2]>5
res=c1&c2&c3
product=product_data[res]
print(product)

[[79.99  4.5   8.  ]]
